pipeline{
    agent any
    stages{ 
        stage("Clean up"){
            steps{
                deleteDir()
            }
        }
        stage("runing python"){
            steps{
                dir("Jenkins/flask_web"){
                    sh "/usr/bin/python3 hello_world_web.py"
                }
            }
        }
    }
}