pipeline{
    agent any
    stages{
        stage("runing python"){
            steps{
                dir("4_hello_word_with_scm_poll"){
                    sh "/usr/bin/python3 hello_world.py"
                }
            }
        }
    }
}