pipeline{
    agent any
    stages{ 
        stage("Clean up"){
            steps{
                deleteDir()
            }
        }
        stage("Clone repo"){ 
            steps{
                sh "git clone https://github.com/Mohitduklan/Jenkins.git"
            }
        }
        stage("runing python"){
            steps{
                dir("Jenkins/flask_web"){ // changing directory
                    sh "which python3"
                    sh "/usr/bin/python3 hello_world_web.py"
                }
            }
        }
    }
}