pipeline{
    agent any // node or slave this should run on
    stages{ 
        // Set of steps
        stage("Clean up"){ // name of step
            steps{
                // Step 1
                deleteDir()
            }
        }
        stage("Clone repo"){
            steps{
                sh "git clone https://github.com/jenkins-docs/simple-java-maven-app.git"
            }
        }
        stage("Build app"){
            steps{
                dir("simple-java-maven-app"){
                    sh "mvn clean install"
                }
            }
        }
        stage("Test app"){
            steps{
                dir("simple-java-maven-app"){
                    sh "mvn test"
                }
            }
        }
    }

}